/* Generated By:JavaCC: Do not edit this line. CompactParserConstants.java */
package edu.stanford.smi.protegex.owl.model.classparser.compact;

public interface CompactParserConstants {

  int EOF = 0;
  int OPENPAR = 6;
  int CLOSEPAR = 7;
  int OPENSQPAR = 8;
  int CLOSESQPAR = 9;
  int UNBOUNDEDVAL = 10;
  int SINGLE_LINE_COMMENT = 14;
  int FORMAL_COMMENT = 15;
  int MULTI_LINE_COMMENT = 16;
  int INTEGER_LITERAL = 18;
  int FLOATING_POINT_LITERAL = 19;
  int EXPONENT = 20;
  int STRING_LITERAL = 21;
  int ONE_OF = 22;
  int IDENTIFIER = 23;
  int DATATYPEID = 24;
  int LETTER = 25;
  int DIGIT = 26;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"..\"",
    "\"//\"",
    "<token of kind 12>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 17>",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"owl:oneOf{\"",
    "<IDENTIFIER>",
    "<DATATYPEID>",
    "<LETTER>",
    "<DIGIT>",
    "\"|\"",
    "\"&\"",
    "\"!\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"$\"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "\"?\"",
    "\",\"",
  };

}
