package edu.stanford.smi.protegex.owlx.examples.javaDemo.model;

import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFSNamedClass;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 *
 * @version generated on Mon Feb 21 10:53:08 EST 2005
 */
public class MyFactory {

    private OWLModel owlModel;


    public MyFactory(OWLModel owlModel) {
        this.owlModel = owlModel;
    }


    public RDFSNamedClass getVeryGoodCustomerClass() {
        final String uri = "http://www.owl-ontologies.com/javaDemo.owl#VeryGoodCustomer";
        final String name = owlModel.getResourceNameForURI(uri);
        return owlModel.getRDFSNamedClass(name);
    }


    public VeryGoodCustomer createVeryGoodCustomer(String name) {
        final RDFSNamedClass cls = getVeryGoodCustomerClass();
        return (VeryGoodCustomer) cls.createInstance(name).as(VeryGoodCustomer.class);
    }


    public RDFSNamedClass getCustomerClass() {
        final String uri = "http://www.owl-ontologies.com/javaDemo.owl#Customer";
        final String name = owlModel.getResourceNameForURI(uri);
        return owlModel.getRDFSNamedClass(name);
    }


    public Customer createCustomer(String name) {
        final RDFSNamedClass cls = getCustomerClass();
        return (Customer) cls.createInstance(name).as(Customer.class);
    }


    public RDFSNamedClass getPurchaseClass() {
        final String uri = "http://www.owl-ontologies.com/javaDemo.owl#Purchase";
        final String name = owlModel.getResourceNameForURI(uri);
        return owlModel.getRDFSNamedClass(name);
    }


    public Purchase createPurchase(String name) {
        final RDFSNamedClass cls = getPurchaseClass();
        return (Purchase) cls.createInstance(name).as(Purchase.class);
    }


    public RDFSNamedClass getProductClass() {
        final String uri = "http://www.owl-ontologies.com/javaDemo.owl#Product";
        final String name = owlModel.getResourceNameForURI(uri);
        return owlModel.getRDFSNamedClass(name);
    }


    public Product createProduct(String name) {
        final RDFSNamedClass cls = getProductClass();
        return (Product) cls.createInstance(name).as(Product.class);
    }


    public RDFSNamedClass getGoodCustomerClass() {
        final String uri = "http://www.owl-ontologies.com/javaDemo.owl#GoodCustomer";
        final String name = owlModel.getResourceNameForURI(uri);
        return owlModel.getRDFSNamedClass(name);
    }


    public GoodCustomer createGoodCustomer(String name) {
        final RDFSNamedClass cls = getGoodCustomerClass();
        return (GoodCustomer) cls.createInstance(name).as(GoodCustomer.class);
    }
}
