package edu.stanford.smi.protegex.owlx.examples.javaDemo.model;

import edu.stanford.smi.protegex.owl.model.RDFIndividual;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/javaDemo.owl#Customer
 *
 * @version generated on Sat Feb 19 17:10:28 EST 2005
 */
public interface Customer_ extends RDFIndividual {

    // Property http://www.owl-ontologies.com/javaDemo.owl#firstName


    String getFirstName();


    RDFProperty getFirstNameProperty();


    boolean hasFirstName();


    void setFirstName(String newFirstName);

    // Property http://www.owl-ontologies.com/javaDemo.owl#lastName


    String getLastName();


    RDFProperty getLastNameProperty();


    boolean hasLastName();


    void setLastName(String newLastName);

    // Property http://www.owl-ontologies.com/javaDemo.owl#purchases


    Collection getPurchases();


    RDFProperty getPurchasesProperty();


    boolean hasPurchases();


    Iterator listPurchases();


    void addPurchases(Purchase newPurchases);


    void removePurchases(Purchase oldPurchases);


    void setPurchases(Collection newPurchases);

    // Property http://www.owl-ontologies.com/javaDemo.owl#zipCode


    int getZipCode();


    RDFProperty getZipCodeProperty();


    boolean hasZipCode();


    void setZipCode(int newZipCode);
}
