package edu.stanford.smi.protegex.owlx.examples.javaDemo.model;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/javaDemo.owl#VeryGoodCustomer
 *
 * @version generated on Mon Feb 21 10:30:47 EST 2005
 */
public interface VeryGoodCustomer extends Customer {

}
