package edu.stanford.smi.protegex.owlx.examples.javaDemo.model;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/javaDemo.owl#GoodCustomer
 *
 * @version generated on Mon Feb 21 10:30:42 EST 2005
 */
public interface GoodCustomer extends Customer {

}
