package edu.stanford.smi.protegex.owlx.examples.javaDemo.model.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owlx.examples.javaDemo.model.VeryGoodCustomer;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/javaDemo.owl#VeryGoodCustomer
 *
 * @version generated on Mon Feb 21 10:30:47 EST 2005
 */
public class DefaultVeryGoodCustomer extends DefaultCustomer
        implements VeryGoodCustomer {

    public DefaultVeryGoodCustomer(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultVeryGoodCustomer() {
    }
}
