/* Generated By:JavaCC: Do not edit this line. ManchesterOWLParserConstants.java */
package edu.stanford.smi.protegex.owl.model.classparser.manchester;

public interface ManchesterOWLParserConstants {

  int EOF = 0;
  int SOME = 6;
  int ALL = 7;
  int HAS = 8;
  int MIN = 9;
  int MAX = 10;
  int EXACT = 11;
  int AND = 12;
  int OR = 13;
  int NOT = 14;
  int OPENPAR = 15;
  int CLOSEPAR = 16;
  int OPENSQPAR = 17;
  int CLOSESQPAR = 18;
  int UNBOUNDEDVAL = 19;
  int CLASS_EXPR_COMMENT = 20;
  int INTEGER_LITERAL = 21;
  int FLOATING_POINT_LITERAL = 22;
  int EXPONENT = 23;
  int STRING_LITERAL = 24;
  int ONE_OF = 25;
  int IDENTIFIER = 26;
  int DATATYPEID = 27;
  int LETTER = 28;
  int DIGIT = 29;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SOME>",
    "<ALL>",
    "<HAS>",
    "<MIN>",
    "<MAX>",
    "<EXACT>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"..\"",
    "\"//\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"owl:oneOf{\"",
    "<IDENTIFIER>",
    "<DATATYPEID>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\",\"",
  };

}
