package edu.stanford.smi.protegex.owlx.examples.javaDemo.model.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owlx.examples.javaDemo.model.GoodCustomer;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/javaDemo.owl#GoodCustomer
 *
 * @version generated on Mon Feb 21 10:30:42 EST 2005
 */
public class DefaultGoodCustomer extends DefaultCustomer
        implements GoodCustomer {

    public DefaultGoodCustomer(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultGoodCustomer() {
    }
}
